'use client'

import { useEffect, useState } from 'react'
import { Activity, ArrowUpRight, BarChart3, BookOpen, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, FileText, Headphones, LayoutDashboard, Menu, MessageSquare, Package, PanelLeft, Send, ShieldCheck, Sparkles, Users, X } from 'lucide-react'

type Snapshot = { connected: boolean; products: { id: string; name?: string; title?: string; status?: string }[]; members: number | null; memberships: number | null; payments: number | null; community: { posts: number | null; activeMembers: number | null }; syncedAt: string; error?: string }

const nav = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Agent', icon: Sparkles }, { label: 'Products', icon: Package },
  { label: 'Customers', icon: Users }, { label: 'Support', icon: Headphones }, { label: 'Community', icon: MessageSquare },
  { label: 'Reports', icon: BarChart3 }, { label: 'Approvals', icon: ShieldCheck }, { label: 'Audit log', icon: FileText },
]

export function BusinessDashboard() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null)
  const [active, setActive] = useState('Overview')
  const [menuOpen, setMenuOpen] = useState(false)
  const [prompt, setPrompt] = useState('')
  const [reply, setReply] = useState('')
  const [asking, setAsking] = useState(false)

  useEffect(() => { fetch('/api/dashboard').then((r) => r.json()).then(setSnapshot).catch(() => setSnapshot({ connected: false, products: [], members: null, memberships: null, payments: null, community: { posts: null, activeMembers: null }, syncedAt: new Date().toISOString(), error: 'Unable to reach the dashboard service.' })) }, [])

  async function askAgent() {
    if (!prompt.trim() || asking) return
    setAsking(true); setReply('')
    const response = await fetch('/api/agent', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prompt }) })
    const data = await response.json(); setReply(data.text ?? data.error ?? 'The agent could not complete that request.'); setAsking(false)
  }

  const connected = snapshot?.connected
  const metrics = [
    { label: 'Members', value: snapshot?.members == null ? '—' : snapshot.members.toLocaleString(), note: 'Live from Whop', icon: Users, tone: 'teal' },
    { label: 'Active memberships', value: snapshot?.memberships == null ? '—' : snapshot.memberships.toLocaleString(), note: 'Live from Whop', icon: Activity, tone: 'blue' },
    { label: 'Payments tracked', value: snapshot?.payments == null ? '—' : snapshot.payments.toLocaleString(), note: 'Read-only count', icon: CircleDollarSign, tone: 'amber' },
    { label: 'Products', value: snapshot ? snapshot.products.length.toString() : '—', note: 'Catalog health', icon: Package, tone: 'violet' },
  ]

  return <div className="min-h-screen bg-background text-foreground">
    <aside className={`${menuOpen ? 'translate-x-0' : '-translate-x-full'} fixed inset-y-0 left-0 z-30 flex w-64 flex-col border-r border-border bg-card p-5 transition-transform lg:translate-x-0`}>
      <div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-4" /></div><div><p className="font-semibold tracking-tight">Ismail Group</p><p className="text-xs text-muted-foreground">Business agent</p></div></div><button className="lg:hidden" aria-label="Close menu" onClick={() => setMenuOpen(false)}><X className="size-4" /></button></div>
      <div className="mt-8 flex items-center gap-2 rounded-lg border border-border bg-muted/50 px-3 py-2 text-xs"><span className={`size-2 rounded-full ${connected ? 'bg-emerald-500' : 'bg-amber-500'}`} /><span>{connected ? 'Whop connected' : 'Connecting to Whop'}</span></div>
      <nav className="mt-7 flex-1 space-y-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMenuOpen(false) }} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm transition ${active === label ? 'bg-primary text-primary-foreground shadow-sm' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon className="size-4" />{label}{label === 'Approvals' && <span className="ml-auto rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-semibold text-amber-800">2</span>}</button>)}</nav>
      <div className="rounded-xl border border-border p-3"><p className="text-xs font-medium">Owner workspace</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Private operations, secure approvals, and growth intelligence.</p></div>
    </aside>
    {menuOpen && <button className="fixed inset-0 z-20 bg-foreground/20 lg:hidden" aria-label="Close navigation" onClick={() => setMenuOpen(false)} />}
    <main className="lg:pl-64"><header className="flex h-16 items-center justify-between border-b border-border bg-card/80 px-5 backdrop-blur md:px-8"><div className="flex items-center gap-3"><button className="lg:hidden" aria-label="Open menu" onClick={() => setMenuOpen(true)}><Menu className="size-5" /></button><div><p className="text-xs text-muted-foreground">Wednesday, August 20, 2026</p><h1 className="text-lg font-semibold tracking-tight">{active}</h1></div></div><div className="flex items-center gap-3"><span className="hidden text-xs text-muted-foreground sm:inline">Last sync {snapshot ? new Date(snapshot.syncedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}</span><div className="grid size-8 place-items-center rounded-full bg-secondary text-xs font-semibold">IG</div></div></header>
      <div className="mx-auto max-w-[1500px] p-5 md:p-8"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-primary/15 bg-primary/5 px-3 py-1 text-xs font-medium text-primary"><Sparkles className="size-3" />Growth command center</div><h2 className="max-w-2xl text-3xl font-semibold tracking-tight text-balance md:text-4xl">Build a stronger business, not just more sales.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Your owner-only AI agent turns Whop activity into clear priorities for your products, members, support, and community.</p></div><button onClick={() => setActive('Reports')} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground">View growth report <ArrowUpRight className="size-4" /></button></section>
        {!connected && <div className="mt-7 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><Clock3 className="mt-0.5 size-4 shrink-0" /><div><p className="font-medium">Live Whop sync needs attention</p><p className="mt-1 text-xs leading-5">{snapshot?.error ?? 'Waiting for a server response.'} No demo data is shown.</p></div></div>}
        <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, note, icon: Icon, tone }) => <div key={label} className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><Icon className={`size-4 text-${tone}-600`} /></div><p className="mt-5 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></div>)}</section>
        <section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="rounded-xl border border-border bg-card p-5 md:p-6"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold">Ask your business agent</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Read data, spot opportunities, draft content, or prepare safe actions.</p></div><div className="rounded-lg bg-primary/10 p-2 text-primary"><Sparkles className="size-4" /></div></div><div className="mt-6 flex min-h-32 flex-col justify-between rounded-xl border border-border bg-muted/30 p-4"><p className="text-sm leading-6 text-muted-foreground">{reply || 'Try “What should I focus on this week to improve community retention?”'}</p><div className="mt-5 flex gap-2"><input value={prompt} onChange={(e) => setPrompt(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.nativeEvent.isComposing && e.keyCode !== 229) askAgent() }} placeholder="Ask anything about your business..." className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground" /><button aria-label="Send to agent" onClick={askAgent} disabled={asking} className="grid size-9 shrink-0 place-items-center rounded-lg bg-primary text-primary-foreground disabled:opacity-50"><Send className="size-4" /></button></div></div><div className="mt-4 flex flex-wrap gap-2">{['Find my growth opportunities', 'Draft a community post', 'Summarize support health'].map((item) => <button key={item} onClick={() => setPrompt(item)} className="rounded-full border border-border px-3 py-1.5 text-xs text-muted-foreground hover:bg-muted">{item}</button>)}</div></div>
          <div className="rounded-xl border border-border bg-card p-5 md:p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Focus this week</p><p className="mt-1 text-xs text-muted-foreground">Growth recommendations</p></div><BarChart3 className="size-4 text-muted-foreground" /></div><div className="mt-5 space-y-4">{[['Community rhythm', 'Create 3 educational posts from your top member questions.', BookOpen], ['Member experience', 'Review unanswered support conversations before Friday.', Headphones], ['Product clarity', 'Refresh the onboarding promise on your highest-traffic product.', Package]].map(([title, text, Icon]) => <div key={title as string} className="flex gap-3"><div className="mt-0.5 rounded-md bg-secondary p-2"><Icon className="size-3.5" /></div><div><p className="text-sm font-medium">{title as string}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{text as string}</p></div><ChevronRight className="ml-auto mt-1 size-4 text-muted-foreground" /></div>)}</div></div></section>
        <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border p-5"><div><p className="text-sm font-semibold">Products</p><p className="mt-1 text-xs text-muted-foreground">Live Whop catalog</p></div><button onClick={() => setActive('Products')} className="text-xs font-medium text-primary">View all</button></div><div className="p-5">{snapshot?.products.length ? snapshot.products.slice(0, 4).map((product) => <div key={product.id} className="flex items-center gap-3 border-b border-border py-3 last:border-0"><div className="grid size-8 place-items-center rounded-lg bg-secondary"><Package className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{product.name ?? product.title ?? product.id}</p><p className="text-xs text-muted-foreground">{product.status ?? 'Active'}</p></div><CheckCircle2 className="size-4 text-emerald-600" /></div>) : <p className="py-8 text-center text-sm text-muted-foreground">No products returned from the live sync.</p>}</div></div><div className="rounded-xl border border-border bg-card"><div className="border-b border-border p-5"><p className="text-sm font-semibold">Recent activity</p><p className="mt-1 text-xs text-muted-foreground">Protected agent workspace</p></div><div className="space-y-5 p-5"><div className="flex gap-3"><div className="grid size-8 place-items-center rounded-full bg-primary/10 text-primary"><Sparkles className="size-3.5" /></div><div><p className="text-sm">Agent workspace ready</p><p className="mt-1 text-xs text-muted-foreground">AI tools are gated by owner approval.</p></div></div><div className="flex gap-3"><div className="grid size-8 place-items-center rounded-full bg-secondary"><ShieldCheck className="size-3.5" /></div><div><p className="text-sm">Approval policy active</p><p className="mt-1 text-xs text-muted-foreground">Pricing and major changes require review.</p></div></div></div></div></section>
      </div></main>
  </div>
}
